package com.example.classes

fun main() {
    /** declaring variables **/
    val person = Person("Guilherme","000.000.000-00","test@test.com")
    val anotherPerson = Person("Luana","222.222.222-22","test2@test2.com")

    /** Printing the autogenerated toString() method **/
    println(person)
    println(anotherPerson)

    /** Printing the autogenerated equals() method **/
    println(person.equals(anotherPerson))

    /** Destructuring declaration **/
    val (name,cpf,email) = person // name = "Guilherme", cpf = "000.000.000-00", email = "test@test.com"
    println("name = $name, cpf = $cpf, email=$email")


}

/** Data class responsible for holding a person's information **/
data class Person(var name: String, val cpf: String, var email: String)